import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";

import { ApolloWrapper } from "@/API/Query/apolloWrapper";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Search Pokemon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
